### ISSUE TITLE
missing sound causes crash

### ISSUE THREAD

**Issue by emilybache** [objarni/four-in-a-row-pygame#1]
I tried to play the game. It started alright but then when I tried to drop a token it crashed with this stacktrace:

emily:four-in-a-row-pygame/ (master*) $ python main.py                                                                                         [16:29:16]
pygame 2.0.0.dev12 (SDL 2.0.12, python 3.8.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    main()
  File "/Users/emily/workspace/playground/four-in-a-row-pygame/src/four_in_a_row.py", line 22, in main
    mainloop(drawing_api, audio_api)
  File "/Users/emily/workspace/playground/four-in-a-row-pygame/src/four_in_a_row.py", line 35, in mainloop
    model = update(model, Tick(pygame.time.get_ticks()), audio_api)
  File "/Users/emily/workspace/playground/four-in-a-row-pygame/src/update.py", line 40, in update
    return update_gamestate(model, msg, audio_api)
  File "/Users/emily/workspace/playground/four-in-a-row-pygame/src/update.py", line 54, in update_gamestate
    gamestate = update(gamestate, ColumnWasClicked(convert_to_column(gamestate.mouse_pos[0])), audio_api)
  File "/Users/emily/workspace/playground/four-in-a-row-pygame/src/update.py", line 40, in update
    return update_gamestate(model, msg, audio_api)
  File "/Users/emily/workspace/playground/four-in-a-row-pygame/src/update.py", line 67, in update_gamestate
    audio_api.play_sound('drop')
  File "/Users/emily/workspace/playground/four-in-a-row-pygame/src/four_in_a_row.py", line 115, in play_sound
    self.sound[name] = pygame.mixer.Sound(p)
FileNotFoundError: No such file or directory.

**Comment by objarni** [comment]
Ah, thanks, will fix tonight! Meanwhile you could check if there is a drop2.wav file, I renamed it iirc

**Comment by objarni** [comment]
Fixed, thanks!
